FROM solr:8
LABEL maintainer="hosting@lyrasis.org"

ENV ARCLIGHT_CONFIGSET_PATH=/opt/solr/server/solr/configsets/arclight/conf
ENV SOLR_MODULES=analysis-extras

USER root

RUN mkdir -p $ARCLIGHT_CONFIGSET_PATH
COPY * $ARCLIGHT_CONFIGSET_PATH/
RUN chown -R solr:solr $ARCLIGHT_CONFIGSET_PATH

USER solr
