---
services:
  solr:
    image: lyrasis/arclight-solr
    build:
      context: ./solr/conf
      dockerfile: Dockerfile
    command: solr-create -c arclight -d arclight
    environment:
      SOLR_OPTS: "-Dsolr.config.lib.enabled=true"
    ports:
      - "8983:8983"
    volumes:
      - ./solr/conf:/opt/solr/server/solr/configsets/arclight/conf
