---
services:
  solr:
    image: solr:8
    command: solr-create -c arclight -d arclight
    ports:
      - "8983:8983"
    volumes:
      - ./solr/conf:/opt/solr/server/solr/configsets/arclight/conf
