default:
  disabled: true
  # pdf:
  #   template: "http://example.com/%{unitid}.pdf"
  # ead:
  #   template: "https://findingaids.lyrasistechnology.org/demo/%{eadid[0..1]}/%{eadid[2..3]}/%{eadid}.xml"
