---
lyrasis-corporate-archive:
  name: Lyrasis Corporate Archive
  visit_notes: Please contact us to schedule a visit.
  description: A wonderful corporate archive for testing (DEMO).
  building: Building 38, Room 1E-21
  contact_html: |
    <div class="al-repository-contact-info">Contact Info</div>
  location_html: |
    <div class="al-repository-location">
      <div class="al-repository-building">Lyrasis</div>
      <div class="al-repository-address">3390 Peachtree Road, NE</div>
      <div class="al-repository-city">Atlanta</div>
      <div class="al-repository-state">GA</div>
      <div class="al-repository-zip">30326</div>
      <div class="al-repository-country">USA</div>
    </div>
  thumbnail_url: https://lyrasisnow.org/wp-content/uploads/2023/03/Lyrasis-Logo-w-Tagline.png
  google_request_url: ""
  google_request_mappings: ""

lyrasis-special-collections:
  name: Lyrasis Special Collections
  visit_notes: Please contact us to schedule a visit.
  description: A wonderful special collections archive for testing (DEMO).
  building: Building 38, Room 1E-21
  contact_html: |
    <div class="al-repository-contact-info">Contact Info</div>
  location_html: |
    <div class="al-repository-location">
      <div class="al-repository-building">Lyrasis</div>
      <div class="al-repository-address">3390 Peachtree Road, NE</div>
      <div class="al-repository-city">Atlanta</div>
      <div class="al-repository-state">GA</div>
      <div class="al-repository-zip">30326</div>
      <div class="al-repository-country">USA</div>
    </div>
  thumbnail_url: https://lyrasisnow.org/wp-content/uploads/2023/03/Lyrasis-Logo-w-Tagline.png
  google_request_url: ""
  google_request_mappings: ""

lyrasis-test:
  name: Lyrasis Test Repository
  visit_notes: Please contact us to schedule a visit.
  description: A wonderful test repository for testing (QA).
  building: Building 38, Room 1E-21
  contact_html: |
    <div class="al-repository-contact-info">Contact Info</div>
  location_html: |
    <div class="al-repository-location">
      <div class="al-repository-building">Lyrasis</div>
      <div class="al-repository-address">3390 Peachtree Road, NE</div>
      <div class="al-repository-city">Atlanta</div>
      <div class="al-repository-state">GA</div>
      <div class="al-repository-zip">30326</div>
      <div class="al-repository-country">USA</div>
    </div>
  thumbnail_url: https://lyrasisnow.org/wp-content/uploads/2023/03/Lyrasis-Logo-w-Tagline.png
  google_request_url: ""
  google_request_mappings: ""
