---
repository: projectblacklight/arclight
version_type: branch
version_ref: main
# version_type: ref
# version: 086061a3e6713d27207d18d929311c3e2e695abd

operations:
  append:
    - file: ".dockerignore"
      text: "/config/locales/en.yml\n"
    - file: ".dockerignore"
      text: "/config/repositories.yml\n"
    - file: ".dockerignore"
      text: "/public/styles.css\n"
    - file: ".gitignore"
      text: "/config/locales/en.yml\n"
    - file: ".gitignore"
      text: "/config/repositories.yml\n"
    - file: ".gitignore"
      text: "/.kamal/secrets\n"
    - file: ".gitignore"
      text: "/public/styles.css\n"
    - file: "Procfile.dev"
      text: "solr: docker compose up\n"
  copy:
    - file: "files/_footer.html.erb"
      to: "app/views/shared/_footer.html.erb"
    - file: "files/.standard.yml"
      to: ".standard.yml"
    - file: "files/deploy.yml"
      to: "config/deploy.yml"
    - file: "files/docker-compose.yml"
      to: "docker-compose.yml"
    - file: "files/docker-compose-qa.yml"
      to: "docker-compose-qa.yml"
    - file: "files/docker-setup"
      to: ".kamal/hooks/docker-setup"
      mode: "0755"
    - file: "files/Dockerfile.solr"
      to: "solr/conf/Dockerfile"
    - file: "files/secrets"
      to: ".kamal/secrets"
    - file: "files/site.rake"
      to: "lib/tasks/site.rake"
    - file: "files/static_controller.rb"
      to: "app/controllers/static_controller.rb"
  create:
    - file: "app/views/static/index.html.erb"
      text: "<h1>Placeholder</h1>"
    - file: "public/styles.css"
      text: "/* Site specific CSS (not asset-pipelined) */"
  insert:
    - file: "bin/docker-entrypoint"
      after: "./bin/rails db:prepare\n"
      text: "./bin/rake site:setup\n"
  remove:
    - ".rubocop.yml"
    - ".solr_wrapper.yml"
    - "app/javascript/controllers/hello_controller.js"
    - "app/views/layouts/application.html.erb"
  replace:
    - file: "Dockerfile"
      from: "chown -R rails:rails.*"
      to: "chown -R rails:rails app config db log public storage tmp"
    - file: "config/database.yml"
      from: "# database: path/to/persistent/storage/production.sqlite3"
      to: "database: storage/production.sqlite3"
    - file: "config/routes.rb"
      from: "arclight.*epositories.index"
      to: "static#index"
    - file: "config/environments/production.rb"
      from: "config.assume_ssl = true"
      to: "config.assume_ssl = ENV.fetch('RAILS_ASSUME_SSL', true) == 'true'"
    - file: "config/environments/production.rb"
      from: "config.force_ssl = true"
      to: "config.force_ssl = ENV.fetch('RAILS_FORCE_SSL', true) == 'true'"
