---
repository: projectblacklight/arclight
version_type: branch
version_ref: main
# version_type: ref
# version: 086061a3e6713d27207d18d929311c3e2e695abd

operations:
  append:
    - file: ".dockerignore"
      text: "/config/locales/en.yml\n"
    - file: ".dockerignore"
      text: "/config/repositories.yml\n"
    - file: ".dockerignore"
      text: "/public/styles.css\n"
    - file: ".gitignore"
      text: "/config/locales/en.yml\n"
    - file: ".gitignore"
      text: "/config/repositories.yml\n"
    - file: ".gitignore"
      text: "/public/styles.css\n"
    - file: "Procfile.dev"
      text: "solr: docker compose up\n"
  copy:
    - file: "files/.standard.yml"
      to: ".standard.yml"
    - file: "files/docker-compose.yml"
      to: "docker-compose.yml"
    - file: "files/_footer.html.erb"
      to: "app/views/shared/_footer.html.erb"
  create:
    - file: "public/styles.css"
      text: "/* Site specific CSS (not asset-pipelined) */"
  remove:
    - ".rubocop.yml"
    - ".solr_wrapper.yml"
    - "app/javascript/controllers/hello_controller.js"
    - "app/views/layouts/application.html.erb"
