---
repository: projectblacklight/arclight
version_type: branch
version_ref: main
# version_type: ref
# version: 086061a3e6713d27207d18d929311c3e2e695abd

operations:
  # appends text to files
  append:
    - file: ".gitignore"
      text:
        - "/app/assets/images/logo.png\n"
        - "/app/assets/images/logo.webp\n"
        - "/app/views/static/index.html.erb\n"
        - "/config/downloads.yml\n"
        - "/config/locales/en.yml\n"
        - "/config/repositories.yml\n"
        - "/.kamal/secrets\n"
        - "/public/logo.png\n"
        - "/public/logo.webp\n"
        - "/public/styles.css\n"
    - file: "Procfile.dev"
      text:
        - "solr: docker compose build && docker compose up\n"

  # copies files from dirs within the files folder to arclight
  copy:
    - from: "app"
      files:
        - file: ".standard.yml"
          to: ".standard.yml"
        - file: "img_embed_component.rb"
          to: "app/components/arclight/img_embed_component.rb"
        - file: "img_embed_component.html.erb"
          to: "app/components/arclight/img_embed_component.html.erb"
        - file: "static_controller.rb"
          to: "app/controllers/static_controller.rb"
        - file: "site.rake"
          to: "lib/tasks/site.rake"
        - file: "top_navbar_component.html.erb"
          to: "app/components/blacklight/top_navbar_component.html.erb"
    - from: "deploy"
      files:
        - file: "deploy.yml"
          to: "config/deploy.yml"
        - file: "secrets"
          to: ".kamal/secrets"
    - from: "docker"
      files:
        - file: "docker-compose.yml"
          to: "docker-compose.yml"
        - file: "docker-compose-qa.yml"
          to: "docker-compose-qa.yml"
        - file: "docker-setup"
          to: ".kamal/hooks/docker-setup"
          mode: "0755"
        - file: "Dockerfile.solr"
          to: "solr/conf/Dockerfile"

  # creates new files in arclight
  create:
    - file: "app/views/static/.gitkeep"
      text: "# This directory is intentionally left blank"
    - file: "app/views/static/index.html.erb"
      text: "<h1>Placeholder</h1>"
    - file: "public/styles.css"
      text: "/* Site specific CSS (not asset-pipelined) */"

  # inserts new text into files at a specific location
  insert:
    - file: "bin/docker-entrypoint"
      after: "./bin/rails db:prepare\n"
      text: "./bin/rake site:setup\n"

  # removes files from arclight
  remove:
    - ".rubocop.yml"
    - ".solr_wrapper.yml"
    - "app/javascript/controllers/hello_controller.js"
    - "app/views/layouts/application.html.erb"

  # replaces text in files
  replace:
    - file: "Dockerfile"
      from: "chown -R rails:rails.*"
      to: "chown -R rails:rails app config db log public storage tmp"
    - file: "app/controllers/catalog_controller.rb"
      from: "Arclight::EmbedComponent"
      to: "Arclight::ImgEmbedComponent"
    - file: "config/database.yml"
      from: "# database: path/to/persistent/storage/production.sqlite3"
      to: "database: storage/production.sqlite3"
    - file: "config/routes.rb"
      from: "arclight.*epositories.index"
      to: "static#index"
    - file: "config/environments/production.rb"
      from: "config.assume_ssl = true"
      to: "config.assume_ssl = ENV.fetch('RAILS_ASSUME_SSL', true) == 'true'"
    - file: "config/environments/production.rb"
      from: "config.force_ssl = true"
      to: "config.force_ssl = ENV.fetch('RAILS_FORCE_SSL', true) == 'true'"
