---
services:
  arclight:
    image: lyrasis/arclight
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ARCLIGHT_SITE=lyrasis
      - RAILS_ASSUME_SSL=false
      - RAILS_ENV=production
      - RAILS_FORCE_SSL=false
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=secret
      - SOLR_URL=http://solr:8983/solr/blacklight-core

  solr:
    image: solr:8
    command: solr-create -c blacklight-core -d arclight
    ports:
      - "8983:8983"
    volumes:
      - ./solr/conf:/opt/solr/server/solr/configsets/arclight/conf
